### ISSUE TITLE
Add Loader while Data loads

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [mhdaxif/pokemon-app#1]
Good to have

**Comment by mhdaxif** [comment]
The loading spinner has been added to indicate data loading. Closing this issue now.

Thanks!

**Comment by muhammadawaisshaikh** [comment]
Sure thanks,

__
Regards,

*Muhammad Awais*
*P: *+923312737076
*E:* ***@***.***
*W:* https://bit.ly/muhammadawaisshaikh
*Video Intro: *https://youtu.be/89t-cRNvfMU
*All Links:* https://linktr.ee/mawaisshaikh
*Linkedin:* www.linkedin.com/in/muhammadawaisshaikh
*Github: *www.github.com/muhammadawaisshaikh
